workflows:
  react-native-expo-android:
    name: React Native Expo Android
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20
    working_directory: my-expo-app
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Cleanup
        script: |
          rm -rf android
      - name: Create google-services.json
        script: echo $GOOGLE_SERVICES_JSON | base64 --decode > google-services.json
      - name: Expo Prebuild
        script: npx expo prebuild --platform android
      - name: Build Android APK
        script: |
          export NODE_OPTIONS="--max-old-space-size=8192"
          cd android
          ./gradlew assembleRelease --no-daemon --stacktrace --info
    artifacts:
      - "**/build/outputs/apk/release/*.apk"
    publishing:
      email:
        recipients:
          - dineshwebdev2003@gmail.com
