workflows:
  react-native-expo-android:
    name: React Native Expo Android
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - firebase
      node: 20
      java: 17
    working_directory: my-expo-app
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Cleanup
        script: |
          rm -rf android
      - name: Create google-services.json
        script: |
          echo $GOOGLE_SERVICES_JSON | base64 --decode > google-services.json
          # Verify the file was created and isn't empty
          if [ ! -s google-services.json ]; then
            echo "ERROR: google-services.json is empty or was not created. Check your Codemagic Environment Variables!"
            exit 1
          fi
      - name: Expo Prebuild
        script: npx expo prebuild --platform android
      - name: Build Android APK
        script: |
          export NODE_OPTIONS="--max-old-space-size=8192"
          cd android
          chmod +x gradlew
          ./gradlew clean assembleDebug --no-daemon --stacktrace
    artifacts:
      - "**/build/outputs/apk/debug/*.apk"
    publishing:
      email:
        recipients:
          - dineshwebdev2003@gmail.com
